# Generated by Django 5.1.1 on 2024-10-09 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventapp', '0002_alter_event_organizer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('S1', 'S1'), ('S3', 'S3'), ('S5', 'S5'), ('S7', 'S7')], max_length=5)),
                ('branch', models.CharField(choices=[('CSA', 'CSA'), ('CSB', 'CSB'), ('AIDS', 'AIDS'), ('CY', 'CY'), ('AI', 'AI'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
