# Generated by Django 5.1.1 on 2024-10-10 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventapp', '0002_alter_event_organizer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('S1', 'S1'), ('S3', 'S3'), ('S5', 'S5'), ('S7', 'S7')], max_length=3)),
                ('class_name', models.CharField(choices=[('CSA', 'CSA'), ('CSB', 'CSB'), ('AIDS', 'AIDS'), ('CS AI', 'CS AI'), ('CY', 'CY'), ('ME', 'ME'), ('CE', 'CE'), ('EEE', 'EEE'), ('ECE', 'ECE')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('media', 'Media'), ('decoration', 'Decoration'), ('management', 'Management'), ('finance', 'Finance'), ('reception', 'Reception Team')], max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
