# Generated by Django 5.1.1 on 2024-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='class_name',
            field=models.CharField(choices=[('CSA', 'CSA'), ('CSB', 'CSB'), ('AIDS', 'AIDS'), ('AI', 'AI'), ('CY', 'CY'), ('ME', 'ME'), ('CE', 'CE'), ('EEE', 'EEE'), ('ECE', 'ECE')], max_length=10),
        ),
    ]
